name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.19
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager --update

    - name: Install specific Android Build Tools and NDK
      run: |
        sdkmanager "build-tools;30.0.3" "ndk;25b"

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get install -y libltdl-dev libffi-dev libssl-dev autoconf autotools-dev
        sudo apt-get install -y zlib1g-dev libbz2-dev libxml2-dev libxslt1-dev
        sudo apt-get install -y libgdbm-dev libreadline-dev wget libncursesw5-dev libsqlite3-dev tk-dev
        sudo apt-get install -y libfreetype6-dev libpng-dev

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: black-jack-app
        path: bin/*.apk