name: Build KivyMD App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade Cython==0.29.19 virtualenv
        pip install buildozer
    
    - name: Clear Buildozer cache
      run: rm -rf ~/.buildozer

    - name: Build APK
      env:
        ANDROID_SDK_TOOLS_LICENSE: "24333f8a63b6825ea9c5514f83c2829b004d1fee"
      run: |
        buildozer init
        sed -i 's/^requirements = python3,kivy$/requirements = python3,kivy,kivymd,pillow/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
