name: Build KivyMD App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade Cython==0.29.19 virtualenv
        pip install buildozer
        pip install setuptools

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 'latest'
        accept-android-sdk-licenses: true

    - name: Install additional Android SDK packages
      run: |
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;35.0.0-rc4"

    # - name: Accept licenses
    #   run: |
    #     yes | sdkmanager --licenses

    - name: Build APK
      run: |
        buildozer init
        sed -i 's/^requirements = python3,kivy$/requirements = python3,kivy,kivymd,pillow/' buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk